name: Build and deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: blog-2812
  AZURE_WEBAPP_PACKAGE_PATH: "."
  DOTNET_VERSION: "8.0.x"
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          dotnet-quality: preview

      - name: Install dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration ${{env.BUILD_CONFIGURATION}} --no-restore

      - name: dotnet publish
        run: dotnet publish -c ${{env.BUILD_CONFIGURATION}} -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "${{ env.AZURE_WEBAPP_NAME }}"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
